
services:
  app:
    ports:
      - "9000:9000"
      - "8080:80"
  server:
    ports:
      - "80:80"
  db:
    ports:
      - "3306:3306"
    environment:
      # MYSQL_DATABASE: db
      # MYSQL_USER: user_laravel
      # MYSQL_ROOT_PASSWORD: root_laravel
      # MYSQL_PASSWORD: user1_laravel

